[versions]
# Kotlin and build tools
kotlin = "2.2.21"
androidGradlePlugin = "8.12.3"
googleServices = "4.4.2"

# Compose
composeBom = "2025.11.00"

# AndroidX
appcompat = "1.7.1"
activityCompose = "1.11.0"
core-ktx = "1.17.0"
biometric = "1.1.0"

# Camera
cameraApp = "1.5.1"

# Google
material = "1.13.0"
mlkit-barcode = "17.3.0"
firebase-messaging = "24.0.2"

# Serialization
gson = "2.13.2"

[libraries]
# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose" }

# AndroidX
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }

# Camera
androidx-camera-core-app = { module = "androidx.camera:camera-core", version.ref = "cameraApp" }
androidx-camera-camera2-app = { module = "androidx.camera:camera-camera2", version.ref = "cameraApp" }
androidx-camera-lifecycle-app = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraApp" }
androidx-camera-view-app = { module = "androidx.camera:camera-view", version.ref = "cameraApp" }

# Google
google-material = { module = "com.google.android.material:material", version.ref = "material" }
google-mlkit-barcode = { module = "com.google.mlkit:barcode-scanning", version.ref = "mlkit-barcode" }
google-firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebase-messaging" }

# Serialization
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

[bundles]
compose = [
    "compose-foundation",
    "compose-ui",
    "compose-material3",
    "compose-material-icons",
    "compose-runtime"
]
camera-app = [
    "androidx-camera-core-app",
    "androidx-camera-camera2-app",
    "androidx-camera-lifecycle-app",
    "androidx-camera-view-app"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
